#Ref - https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
apiVersion: v1
kind: Pod
metadata:
  name: postgresapi
  labels:
    app: postgresapi
spec:
  containers:
    - name: postgresapi
      image: nikxgupta/postgresapi:v3
      ports:
        - containerPort: 2112
---
apiVersion: v1
kind: Service
metadata:
  name: service-postgresapi
  labels:
    app: postgresapi
spec:
  type: NodePort
  selector:
      app: postgresapi
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32002

