apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
spec:
  initContainers:
    - name: install-index
      image: busybox
      command:
        - "wget"
        - "-O"
        - "/work-dir/index.html"
        - http://kubernetes.io
      volumeMounts:
        - mountPath: "/work-dir"
          name: nginx-data
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - name: nginx-data
        mountPath: /usr/share/nginx/html
  dnsPolicy: Default
  volumes:
    - name: nginx-data
      emptyDir: {}
  
