apiVersion: v1
kind: Pod
metadata:
  name: lifecyle-hook
spec:
  containers:
    - name: hook-container
      image: nginx
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh","-c","echo Hello pod is starting > /usr/share/message"]
        preStop:
          exec:
            command: ["/usr/sbin/nginx","-s", "quit"]

