apiVersion: v1
kind: Pod
metadata:
  name: pod-kube-app
  labels:
    app: kube-app
spec:
  hostNetwork: true
  containers:
    - name: container-kube-app
      image: nikxgupta/postgresapi:v3
      ports:
        - containerPort: 2112

