apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: redis-app
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - name: nginx-data
        mountPath: /data/nginx
  volumes:
    - name: nginx-data
      emptyDir: {}
  
