apiVersion: v1
kind: Pod
metadata:
  name: pod-kube-app
  labels:
    app: kube-app
spec:
  containers:
    - name: container-kube-app
      image: devignitelab.jfrog.io/labdocker/kube-app:v1
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-kube-app
  labels:
    app: kube-app
spec:
  type: NodePort
  selector:
      app: kube-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32002

