apiVersion: v1
kind: Pod
metadata:
  name: pod-label-selector
  labels:
    env: dev
    app: redis
spec:
  containers:
    - name: container-redis
      image: redis
      ports:
        - containerPort: 6379
  nodeSelector:
    env: dev
      