apiVersion: v1
kind: Pod
metadata:
  name: pod-kube-app
  labels:
    app: kube-app
spec:
  containers:
    - name: container-kube-app
      image: nikxgupta/postgresapi:v3
      ports:
        - containerPort: 2112
---
apiVersion: v1
kind: Service
metadata:
  name: service-kube-app
  labels:
    app: kube-app
spec:
  type: NodePort
  selector:
      app: kube-app
  ports:
    - port: 9091
      targetPort: 2112
      nodePort: 32005

