apiVersion: v1
kind: Pod
metadata:
  name: pod-port-expose
  labels:
    app: nginx-app
spec:
  containers:
    - name: container-port-expose
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  labels:
    app: nginx-app
spec:
  type: NodePort
  selector:
      app: nginx-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32001

