apiVersion: v1
kind: Pod
metadata:
  name: pod-health-probe
spec:
  containers:
    - name: container-health-probe
      image: nikxgupta/redis-app:v1
      env:
        - name: ASPNETCORE_ENVIRONMENT
          value: DEV
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /health
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 20
      readinessProbe:
        httpGet:
          path: /health
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
        
