apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: repl-mongo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: mongo-app
  template:
    metadata:
      labels:
        env: DEV
        name: mongo-app
    spec:
      containers:
        - name: pod-repl-mongo-app
          image: devignitelab.jfrog.io/labdocker/mongo-app:v2
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: DEV
            - name: MongodbConnection
              value: "192.168.118.131"
          ports:
            - containerPort: 80
        