# After deployment run command $ kubectl set image deploy kubia nodejs=luksa/kubia:v3
# Rollout will not succeed because of minReadySeconds and ReadynessProbe
apiVersion: apps/v1         
kind: Deployment                  
metadata:
  name: kubia  
  labels:
    app: kubia                   
spec:
  replicas: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
      - image: luksa/kubia:v1
        name: nodejs
        readinessProbe:
          periodSeconds: 1
          httpGet:
            path: /
            port: 8080
