apiVersion: v1
kind: Secret
metadata:
  name: nikx-secret
type: Opaque
stringData:
  username: something

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-generic-env
spec:
  containers:
    - name: secret-env
      image: nginx
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: nikx-secret
              key: username