apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-generic
spec:
  containers:
    - name: secret-generic
      image: nginx
      volumeMounts:
        - name: generic-secret-volume
          mountPath: /etc/secret-volume
  volumes:
    - name: generic-secret-volume
      secret:
        secretName: nikx-secret

