# run command $ kubectl taint node <node name> cpu=high:NoSchedule
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-label-selector
  labels:
    env: dev
spec:
  replicas: 20
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: container-nginx
          image: nginx
      tolerations:
      - key: "cpu"
        operator: "Equal"
        value: "high"
        effect: "NoSchedule"
        

      