apiVersion: v1
kind: Pod
metadata:
  name: pod-hackube
  labels:
    app: hackube
spec:
  containers:
    - name: container-hackube
      image: nikxgupta/hackube:v1.1
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-hackube
  labels:
    app: hackube
spec:
  type: NodePort
  selector:
      app: hackube
  ports:
    - port: 9091
      targetPort: 8080
      nodePort: 32005

